version: '3.8'
services:
  sqlite-web:
    build: .
    image: instagram-db
    ports:
      - '8080:8080'
    volumes:
      - ./instagram-database.sql:/data/instagram-database.sql:ro
    restart: unless-stopped
